apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app:  backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  backend-feed
  template:
    metadata:
      labels:
        app:  backend-feed
    spec:
      containers:
        - name: backend-feed
          image: docker.io/akem123/udagram-api-feed
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          envFrom:
          - configMapRef:
              name: env-config
          - secretRef:
              name: env-secret